# Generated by Django 4.2.4 on 2023-08-14 09:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_auctionlisting_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='watch_list',
            field=models.ManyToManyField(blank=True, related_name='watch_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
