# Generated by Django 4.2.4 on 2023-08-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auctionlisting_watch_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
