# Generated by Django 4.2.4 on 2023-08-15 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_bids_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='amout',
            new_name='bid',
        ),
        migrations.RemoveField(
            model_name='auctionlisting',
            name='starting_bid',
        ),
        migrations.RemoveField(
            model_name='bids',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='bids',
            name='time',
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='price',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_bid', to='auctions.bids'),
        ),
    ]
