# Generated by Django 4.2.4 on 2023-08-15 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_rename_amout_bids_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='add_comment', to='auctions.comments'),
        ),
    ]
