# Generated by Django 4.2.4 on 2023-08-16 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auctionlisting_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_comment', to='auctions.comments'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.CharField(blank=True, max_length=640, null=True),
        ),
    ]
