# Generated by Django 4.2.4 on 2023-08-19 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auctionlisting_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='listing',
        ),
    ]
